///////////////////////////////////////////////////////////
//  AsignarRepPedido.cs
//  Implementation of the Class AsignarRepPedido
//  Generated by Enterprise Architect
//  Created on:      30-Set.-2017 12:37:43
//  Original author: Enrique
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DeliveryOnline.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DeliveryOnline.Models {

    [Table("AsignarRepPedido", Schema = "Tienda")]
    public class AsignarRepPedido {

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        private DateTime dFechaHoraEntrega;
		private DateTime dFechaHoraSalida;
		private int nEstado;
		public DeliveryOnline.Models.Pedido m_Pedido { get; set; }
		public DeliveryOnline.Models.Repartidor m_Repartidor { get; set; }

		public AsignarRepPedido(){

		}

		~AsignarRepPedido(){

		}

		public int Estado{
			get{
				return nEstado;
			}
			set{
				nEstado = value;
			}
		}


		public DateTime FechaHoraEntrega{
			get{
				return dFechaHoraEntrega;
			}
			set{
				dFechaHoraEntrega = value;
			}
		}

		public DateTime FechaHoraSalida{
			get{
				return dFechaHoraSalida;
			}
			set{
				dFechaHoraSalida = value;
			}
		}

	}//end AsignarRepPedido

}//end namespace Models