///////////////////////////////////////////////////////////
//  DetalleVenta.cs
//  Implementation of the Class DetalleVenta
//  Generated by Enterprise Architect
//  Created on:      29-Set.-2017 12:43:21
//  Original author: Enrique
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DeliveryOnline.Models;
namespace DeliveryOnline.Models {
	public class DetalleVenta {

		private Double nCantidad;
		private Double nPrecio;
		public DeliveryOnline.Models.Producto m_Producto;

		public DetalleVenta(){

		}

		public Double Cantidad{
			get{
				return nCantidad;
			}
			set{
				nCantidad = value;
			}
		}

		public Double Precio{
			get{
				return nPrecio;
			}
			set{
				nPrecio = value;
			}
		}

		/// 
		/// <param name="nCantidad"></param>
		/// <param name="nPrecio"></param>
		public int SubTotal(int nCantidad, double nPrecio){

			return 0;
		}

	}//end DetalleVenta

}//end namespace Models