///////////////////////////////////////////////////////////
//  DetalleVenta.cs
//  Implementation of the Class DetalleVenta
//  Generated by Enterprise Architect
//  Created on:      30-Set.-2017 12:37:43
//  Original author: Enrique
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DeliveryOnline.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DeliveryOnline.Models {

    [Table("DetalleVenta", Schema = "Tienda")]
    public class DetalleVenta {

		private Double nCantidad;
		private Double nPrecio;
		public DeliveryOnline.Models.TiendaProducto m_TiendaProducto { get; set; }

		public DetalleVenta(){

		}

		~DetalleVenta(){

		}

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        [Required]
        public Double Cantidad{
			get{
				return nCantidad;
			}
			set{
				nCantidad = value;
			}
		}

        [Required]
		public Double Precio{
			get{
				return nPrecio;
			}
			set{
				nPrecio = value;
			}
		}

		/// 
		/// <param name="nCantidad"></param>
		/// <param name="nPrecio"></param>
		public int SubTotal(int nCantidad, double nPrecio){

			return 0;
		}

	}//end DetalleVenta

}//end namespace Models