///////////////////////////////////////////////////////////
//  DetallePedido.cs
//  Implementation of the Class DetallePedido
//  Generated by Enterprise Architect
//  Created on:      30-Set.-2017 12:37:43
//  Original author: Enrique
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DeliveryOnline.Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace DeliveryOnline.Models {

    [Table("DetallePedido", Schema = "Tienda")]
    public class DetallePedido {

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }
        private int nCantidad;
		private int nEstado;
		private Double nPrecio;
		public DeliveryOnline.Models.TiendaProducto m_TiendaProducto { get; set; }  

		public DetallePedido(){

		}

		~DetallePedido(){

		}

        [Required]
        public int Cantidad{
			get{
				return nCantidad;
			}
			set{
				nCantidad = value;
			}
		}

		public int Estado{
			get{
				return nEstado;
			}
			set{
				nEstado = value;
			}
		}

        [Required]
        public Double Precio{
			get{
				return nPrecio;
			}
			set{
				nPrecio = value;
			}
		}

		/// 
		/// <param name="ncantidad"></param>
		/// <param name="nprecio"></param>
		public int SubTotal(int ncantidad, double nprecio){

			return 0;
		}

	}//end DetallePedido

}//end namespace Models