///////////////////////////////////////////////////////////
//  TipoDocuCorrelativo.cs
//  Implementation of the Class DocuVentaCorrelativo
//  Generated by Enterprise Architect
//  Created on:      30-Set.-2017 12:37:43
//  Original author: Enrique
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DeliveryOnline.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DeliveryOnline.Models {

    [Table("DocuVentaCorrelativo", Schema = "Documento")]
    public class DocuVentaCorrelativo {

		private int cCorrelativoActual;
		private int cSerie;
		private int Id;
		public DeliveryOnline.Models.Tienda m_Tienda { get; set; }
		public DeliveryOnline.Models.TipoDocuVenta m_TipoDocuVenta { get; set; }

		public DocuVentaCorrelativo(){

		}

		~DocuVentaCorrelativo(){

		}

        [Key()]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CodigoId{
			get{
				return Id;
			}
			set{
				Id = value;
			}
		}

        [Required]
		public int CorrelativoActual{
			get{
				return cCorrelativoActual;
			}
			set{
				cCorrelativoActual = value;
			}
		}

        [Required]
        public int Serie{
			get{
				return cSerie;
			}
			set{
				cSerie = value;
			}
		}

	}//end DocuVentaCorrelativo

}//end namespace Models