///////////////////////////////////////////////////////////
//  Pedido.cs
//  Implementation of the Class Pedido
//  Generated by Enterprise Architect
//  Created on:      30-Set.-2017 12:37:43
//  Original author: Enrique
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DeliveryOnline.Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace DeliveryOnline.Models {

    [Table("Pedido", Schema = "Tienda")]
    public class Pedido {

		private DateTime dFechaHoraEntrega;
		private DateTime dFechaHoraRegistro;
		private int Id;
		private int nEstado;

        [Required]
        public virtual ICollection<DeliveryOnline.Models.DetallePedido> m_DetallePedido { get; set; }

        [Required]
        public DeliveryOnline.Models.Persona m_Persona;

		public Pedido(){

		}

		~Pedido(){

		}

        [Key()]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CodigoId{
			get{
				return Id;
			}
			set{
				Id = value;
			}
		}

		public int Estado{
			get{
				return nEstado;
			}
			set{
				nEstado = value;
			}
		}

        [DataType(DataType.Date)]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Fecha/Hora Entrega")]
        public DateTime FechaHoraEntrega{
			get{
				return dFechaHoraEntrega;
			}
			set{
				dFechaHoraEntrega = value;
			}
		}

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Fecha/Hora Registro")]
        public DateTime FechaHoraRegistro{
			get{
				return dFechaHoraRegistro;
			}
			set{
				dFechaHoraRegistro = value;
			}
		}

        #region Methodos

        /// <summary>
        /// Agrega detalle pedido
        /// </summary>
        /// <param name="detallePedido"></param>
        public void agregarDetallePedido(DeliveryOnline.Models.DetallePedido detallePedido) {
            m_DetallePedido.Add(detallePedido);
        }
        #endregion

    }//end Pedido

}//end namespace Models