///////////////////////////////////////////////////////////
//  Pedido.cs
//  Implementation of the Class Pedido
//  Generated by Enterprise Architect
//  Created on:      30-Set.-2017 12:37:43
//  Original author: Enrique
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DeliveryOnline.Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace DeliveryOnline.Models {

    [Table("Pedido", Schema = "Tienda")]
    public class Pedido {

		private DateTime dFechaHoraEntrega;
		private DateTime dFechaHoraRegistro;
		private int Id;
		private int nEstado;
		public virtual ICollection<DeliveryOnline.Models.DetallePedido> m_DetallePedido { get; set; }
		public DeliveryOnline.Models.Persona m_Persona;

		public Pedido(){

		}

		~Pedido(){

		}

        [Key()]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CodigoId{
			get{
				return Id;
			}
			set{
				Id = value;
			}
		}

		public int Estado{
			get{
				return nEstado;
			}
			set{
				nEstado = value;
			}
		}

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime FechaHoraEntrega{
			get{
				return dFechaHoraEntrega;
			}
			set{
				dFechaHoraEntrega = value;
			}
		}

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime FechaHoraRegistro{
			get{
				return dFechaHoraRegistro;
			}
			set{
				dFechaHoraRegistro = value;
			}
		}

	}//end Pedido

}//end namespace Models