///////////////////////////////////////////////////////////
//  PrecioTienda.cs
//  Implementation of the Class PrecioTienda
//  Generated by Enterprise Architect
//  Created on:      29-Set.-2017 12:43:21
//  Original author: Enrique
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DeliveryOnline.Models;
namespace DeliveryOnline.Models {
	public class PrecioTienda {

		private double nPrecio;
		private int nStock;
		public DeliveryOnline.Models.Producto m_Producto;
		public DeliveryOnline.Models.Tienda m_Tienda;

		public PrecioTienda(){

		}

		~PrecioTienda(){

		}

		public double Precio{
			get{
				return nPrecio;
			}
			set{
				nPrecio = value;
			}
		}

		public int Stock{
			get{
				return nStock;
			}
			set{
				nStock = value;
			}
		}

	}//end PrecioTienda

}//end namespace Models