///////////////////////////////////////////////////////////
//  PrecioTienda.cs
//  Implementation of the Class TiendaProducto
//  Generated by Enterprise Architect
//  Created on:      29-Set.-2017 18:18:27
//  Original author: Enrique
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DeliveryOnline.Models;
namespace DeliveryOnline.Models {
	public class TiendaProducto {

		private double nPrecio;
		private int nStock;
		public DeliveryOnline.Models.Producto m_Producto;
		public DeliveryOnline.Models.Tienda m_Tienda;
		private DeliveryOnline.Models.DetalleVenta m_DetalleVenta;
		private DeliveryOnline.Models.DetallePedido m_DetallePedido;

		public TiendaProducto(){

		}

		public double Precio{
			get{
				return nPrecio;
			}
			set{
				nPrecio = value;
			}
		}

		public int Stock{
			get{
				return nStock;
			}
			set{
				nStock = value;
			}
		}

	}//end TiendaProducto

}//end namespace Models