///////////////////////////////////////////////////////////
//  Producto.cs
//  Implementation of the Class Producto
//  Generated by Enterprise Architect
//  Created on:      29-Set.-2017 12:43:21
//  Original author: Enrique Incio Ch
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DeliveryOnline.Models;
namespace DeliveryOnline.Models {
	public class Producto {

		private string cDescripcion;
		private string cImagen;
		private int Id;
		public DeliveryOnline.Models.PrecioTienda m_PrecioTienda;
		public DeliveryOnline.Models.TiposMenu m_TiposMenu;

		public Producto(){

		}


		public int CodigoId{
			get{
				return Id;
			}
			set{
				Id = value;
			}
		}

		public string descripcion{
			get{
				return cdescripcion;
			}
			set{
				cdescripcion = value;
			}
		}

		public string Imagen{
			get{
				return cImagen;
			}
			set{
				cImagen = value;
			}
		}

	}//end Producto

}//end namespace Models