///////////////////////////////////////////////////////////
//  Producto.cs
//  Implementation of the Class Producto
//  Generated by Enterprise Architect
//  Created on:      30-Set.-2017 12:37:43
//  Original author: Enrique Incio Ch
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DeliveryOnline.Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace DeliveryOnline.Models {

    [Table("Producto", Schema = "Producto")]
    public class Producto {

		private string cDescripcion;
		private string cImagen;
		private int Id;
		public DeliveryOnline.Models.TiendaProducto m_TiendaProducto {get; set; }
        public DeliveryOnline.Models.TiposMenu m_TiposMenu { get; set; }

		public Producto(){

		}

		~Producto(){

		}

        [Key()]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CodigoId{
			get{
				return Id;
			}
			set{
				Id = value;
			}
		}

        [Required]
        [Column("Nombre", TypeName = "varchar", Order = 2)]
        [MaxLength(250), MinLength(10)]
        public string Descripcion{
			get{
				return cDescripcion;
			}
			set{
                cDescripcion = value;
			}
		}

		public string Imagen{
			get{
				return cImagen;
			}
			set{
				cImagen = value;
			}
		}

	}//end Producto

}//end namespace Models