///////////////////////////////////////////////////////////
//  Repartidor.cs
//  Implementation of the Class Repartidor
//  Generated by Enterprise Architect
//  Created on:      29-Set.-2017 12:43:21
//  Original author: Enrique
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DeliveryOnline.Models;
namespace DeliveryOnline.Models {
	public class Repartidor {

		private string cNombre;
		private int Id;
		private int nEstado;
		public DeliveryOnline.Models.Tienda m_Tienda;

		public Repartidor(){

		}

		public int CodigoId{
			get{
				return Id;
			}
			set{
				Id = value;
			}
		}

		public int Estado{
			get{
				return nEstado;
			}
			set{
				nEstado = value;
			}
		}

		public string Nombre{
			get{
				return cNombre;
			}
			set{
				cNombre = value;
			}
		}

	}//end Repartidor

}//end namespace Models