///////////////////////////////////////////////////////////
//  Tienda.cs
//  Implementation of the Class Tienda
//  Generated by Enterprise Architect
//  Created on:      29-Set.-2017 12:43:21
//  Original author: Enrique Incio Ch.
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DeliveryOnline.Models;
namespace DeliveryOnline.Models {
	public class Tienda {

		private string cDireccion;
		private string cNombreComercial;
		private string cRazonSocial;
		private string cTelefono;
		private DateTime dFechaRegsitro;
		private int Id = 0;
		private int nEstado;
		public DeliveryOnline.Models.PrecioTienda m_PrecioTienda;
		public DeliveryOnline.Models.TiendaUsuario m_TiendaUsuario;

		public Tienda(){

		}

		public int CodigoId{
			get{
				return Id;
			}
			set{
				Id = value;
			}
		}

		public string Direccion{
			get{
				return cDireccion;
			}
			set{
				cDireccion = value;
			}
		}

		public int Estado{
			get{
				return nEstado;
			}
			set{
				nEstado = value;
			}
		}

		public DateTime FechaRegsitro{
			get{
				return dFechaRegsitro;
			}
			set{
				dFechaRegsitro = value;
			}
		}

		public string NombreComercial{
			get{
				return cNombreComercial;
			}
			set{
				cNombreComercial = value;
			}
		}

		public string RazonSocial{
			get{
				return cRazonSocial;
			}
			set{
				cRazonSocial = value;
			}
		}

		public string Telefono{
			get{
				return cTelefono;
			}
			set{
				cTelefono = value;
			}
		}

	}//end Tienda

}//end namespace Models