///////////////////////////////////////////////////////////
//  PrecioTienda.cs
//  Implementation of the Class TiendaProducto
//  Generated by Enterprise Architect
//  Created on:      30-Set.-2017 12:37:43
//  Original author: Enrique
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DeliveryOnline.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DeliveryOnline.Models {
	public class TiendaProducto {

		private double nPrecio;
		private int nStock;
        
        [Column(Order = 1), Key]
        public DeliveryOnline.Models.Producto m_Producto { get; set; }
        [Column(Order = 2), Key]
        public DeliveryOnline.Models.Tienda m_Tienda { get; set; }

        [Column(Order = 3), Key]
        public DateTime dFechaEfectiva { get; set; }

        public TiendaProducto(){

		}

		~TiendaProducto(){

		}

		public double Precio{
			get{
				return nPrecio;
			}
			set{
				nPrecio = value;
			}
		}

		public int Stock{
			get{
				return nStock;
			}
			set{
				nStock = value;
			}
		}

	}//end TiendaProducto

}//end namespace Models