///////////////////////////////////////////////////////////
//  PrecioTienda.cs
//  Implementation of the Class TiendaProducto
//  Generated by Enterprise Architect
//  Created on:      30-Set.-2017 12:37:43
//  Original author: Enrique Incio Ch.
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DeliveryOnline.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DeliveryOnline.Models {

    [Table("TiendaProducto", Schema ="Producto")]
	public class TiendaProducto {

        //    [Key, ForeignKey("m_Tienda")]
        //    [Required]
        //    [Column(Order = 1)]
        //    public int m_Tienda_CodigoId { get; set; } 

        [Key, ForeignKey("m_Producto")]
        [Required]
        [Column(Order = 2)]
        public int m_Producto_CodigoId { get; set; } 

        [Key]
        [Required]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        [Column(Order = 3)]
        public DateTime? dFechaEfectiva { get; set; }

        public virtual DeliveryOnline.Models.Producto m_Producto { get; set; }

        //public virtual DeliveryOnline.Models.Tienda m_Tienda { get; set; }

        private double nPrecio;
        private int nStock;

        public TiendaProducto(){

		}

		~TiendaProducto(){

		}

		public double Precio{
			get{
				return nPrecio;
			}
			set{
				nPrecio = value;
			}
		}

		public int Stock{
			get{
				return nStock;
			}
			set{
				nStock = value;
			}
		}

	}//end TiendaProducto

}//end namespace Models