///////////////////////////////////////////////////////////
//  TipoCliente.cs
//  Implementation of the Class TipoCliente
//  Generated by Enterprise Architect
//  Created on:      29-Set.-2017 12:43:22
//  Original author: Enrique
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace DeliveryOnline.Models {
	public class TipoCliente {

		private string cDescripcion;
		private int Id;

		public TipoCliente(){

		}

		public int CodigoId{
			get{
				return id;
			}
			set{
				id = value;
			}
		}

		public string Descripcion{
			get{
				return cDescripcion;
			}
			set{
				cDescripcion = value;
			}
		}

	}//end TipoCliente

}//end namespace Models