///////////////////////////////////////////////////////////
//  TipoCliente.cs
//  Implementation of the Class TipoCliente
//  Generated by Enterprise Architect
//  Created on:      30-Set.-2017 12:37:43
//  Original author: Enrique
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace DeliveryOnline.Models {

    [Table("TipoCliente", Schema = "Persona")]
    public class TipoCliente {

		private string cDescripcion;
		private int Id;

		public TipoCliente(){

		}

		~TipoCliente(){

		}

        [Key()]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ClienteId{
			get{
				return Id;
			}
			set{
				Id = value;
			}
		}

        [Required]
        [Column("Descripcion", TypeName = "varchar", Order = 2)]
        [MaxLength(250), MinLength(5)]
        [DisplayName("Descripción")]
        public string Descripcion{
			get{
				return cDescripcion;
			}
			set{
				cDescripcion = value;
			}
		}

	}//end TipoCliente

}//end namespace Models