///////////////////////////////////////////////////////////
//  TipoDocuVenta.cs
//  Implementation of the Class TipoDocuVenta
//  Generated by Enterprise Architect
//  Created on:      30-Set.-2017 12:37:44
//  Original author: Enrique
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DeliveryOnline.Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace DeliveryOnline.Models {

    [Table("TipoDocuVenta", Schema = "Documento")]
    public class TipoDocuVenta {

		private string cDescripcion;
		private int Id;
		//public DeliveryOnline.Models.DocuVentaCorrelativo m_DocuVentaCorrelativo;

		public TipoDocuVenta(){

		}

		~TipoDocuVenta(){

		}

        [Key()]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CodigoId{
			get{
				return Id;
			}
			set{
				Id = value;
			}
		}

        [Required]
        [DisplayName("Nombres")]
        [ConcurrencyCheck, MaxLength(10, ErrorMessage = "Nombre debe tener 7 caracteres o menos"), MinLength(5)]
        public string Descripcion{
			get{
				return Descripcion;
			}
			set{
				Descripcion = value;
			}
		}

	}//end TipoDocuVenta

}//end namespace Models