///////////////////////////////////////////////////////////
//  Venta.cs
//  Implementation of the Class Venta
//  Generated by Enterprise Architect
//  Created on:      30-Set.-2017 12:37:44
//  Original author: Enrique
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DeliveryOnline.Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace DeliveryOnline.Models {

    [Table("Venta", Schema = "Tienda")]
    public class Venta {

		private string cCorrelativo;
		private string cSerie;
		private DateTime dFechaPago;
		private DateTime dFechaRegistro;
		private int Id;

        [Required]
        public DeliveryOnline.Models.DocuVentaCorrelativo m_DocuVentaCorrelativo { get; set; }
        [Required]
        public DeliveryOnline.Models.Pedido m_Pedido { get; set; }
        [Required]
        public List<DeliveryOnline.Models.DetalleVenta> m_DetalleVenta { get; set; }
        [Required]
        public DeliveryOnline.Models.Persona m_Persona { get; set; }

		public Venta(){

		}

		~Venta(){

		}

        [Key()]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CodigoId{
			get{
				return Id;
			}
			set{
				Id = value;
			}
		}

        //This allows null

        public DateTime FechaPago{
			get{
				return dFechaPago;
			}
			set{
				dFechaPago = value;
			}
		}

		public DateTime FechaRegistro{
			get{
				return dFechaRegistro;
			}
			set{
				dFechaRegistro = value;
			}
		}

        [Required]
        public string Serie{
			get{
				return cSerie;
			}
			set{
				cSerie = value;
			}
		}

        [Required]
        public string Correlativo
        {
            get
            {
                return cCorrelativo;
            }
            set
            {
                cCorrelativo = value;
            }
        }
    }//end Venta

}//end namespace Models